[scheduler]
log_level = "warn"
tick_interval_ms = 1000
max_concurrency = 100000
shards = 4
scheduler_shards = 1
pin_shards_to_cores = false
cpu_affinity_offset = 0

[database]
host = "127.0.0.1"
port = 3306
username = "root"
password = "604222352mj"
database = "dagforge_perf16"
pool_size = 64

[api]
enabled = true
host = "127.0.0.1"
port = 8888
reuse_port = false

[dag_source]
directory = "./bench/airflow_dags/scene1_linear_100x10"
scan_interval_sec = 60
